# Generated by Django 4.0.1 on 2023-07-10 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dd', models.CharField(max_length=255)),
                ('vn', models.CharField(max_length=255)),
                ('ep', models.IntegerField()),
                ('dt', models.JSONField()),
            ],
        ),
    ]
